[package]
name = "defi_agent"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }

[addresses]
defi_agent = "0xcafe"

[dev-addresses]
defi_agent = "0x1"
